Repository avocado-framework/avocado-vt, pull requests merged in 2020-11, with the labels that each got.

#2812 Fix up:Update default value of 'nat_attrs' of create_net_xml()
  virttest/utils_test/libvirt.py
Labels: minorfix

#2818 Fix error #2808 brought in: testprovider download dir path changed
  virttest/data_dir.py
Labels: Critical, minorfix

#2802 Extend nbd utils to allow encrypted key
  virttest/utils_nbd.py
Labels: depend on

#2709 Add migration_template.py, also update base.cfg
  virttest/migration.py
  virttest/migration_template.py
  virttest/shared/cfg/base.cfg
Labels: request_2_maintainers
