Repository avocado-framework/avocado-vt, pull requests merged in 2020-08, with the labels that each got.

#2659 Add the server's ip info when the certificates generated
  virttest/utils_nbd.py
Labels: depend on

#2695 Add debug info
  virttest/libvirt_vm.py
Labels: minorfix

#2006 Minorfix: Make a copy for globals to avoid RuntimeError
  virttest/virsh.py
Labels: minorfix

#2711 Fix an issue for TLS
  virttest/utils_conn.py
Labels: minorfix

#2630 Update TLSConnection client_setup() to reuse previous CA cert
  virttest/utils_conn.py
  virttest/utils_nbd.py
Labels: request_2_maintainers

#2727 Remove the dependancy on utils_misc
  virttest/remote.py
  virttest/utils_logfile.py
Labels: request_2_maintainers
