Repository avocado-framework/avocado-vt, pull requests merged in 2020-07, with the labels that each got.

#2621 Fix the stdout error as compat_52lts removed
  virttest/virsh.py
Labels: minorfix

#2620 Fix the error to decode the cmd result
  virttest/virsh.py
Labels: minorfix

#2625 Fix error of replacing exit_status with stdout
  virttest/cpu.py
Labels: minorfix

#2627 Fixup an error while archiving libvirtd debug logs
  avocado_vt/test.py
Labels: request_2_maintainer

#2636 libvirt check: delay the actual check until/if needed
  virttest/libvirtd_decorator.py
Labels: request_2_maintainer

#2647 Update to check libvirt version by 'libvirtd' or 'virtqemud' command
  virttest/libvirt_version.py
Labels: request_2_maintainer

#2646 Add a class for libvirtd/virtdproxy tls and tcp
  virttest/staging/service.py
  virttest/utils_conn.py
  virttest/utils_libvirtd.py
Labels: request_2_maintainers

#2633 Fix polkit configuration issue in split daemon job
  virttest/env_process.py
  virttest/test_setup.py
Labels: depend on, request_2_maintainers

#2631 Update LibvirtdDebugLog to enable debuging log for virt* daemons
  virttest/test_setup.py
Labels: depend on, request_2_maintainers

#2670 Fixup Libvirtd.restart()
  virttest/utils_libvirtd.py
Labels: minorfix
