Repository avocado-framework/avocado-vt, pull requests merged in 2021-09, with the labels that each got.

#3121 Support nest virt on host
  virttest/utils_libvirt/libvirt_nested.py
Labels: depend on

#3206 sriov: Add timeout to set_vf
  virttest/utils_sriov.py
Labels: minorfix

#3211 Cartesian parser fix in resolver
  avocado_vt/plugins/vt_resolver.py
Labels: bug

#3234 v2v: make images into default image path when converting vm to libvirt
  virttest/backends/v2v/cfg/convert_destination.cfg
Labels: minorfix, depend on

#3223 virsh: Remove redundant code
  virttest/virsh.py
Labels: minorfix

#3228 vm_xml: Update super class from VMXML to base.LibvirtXMLBase
  virttest/libvirt_xml/vm_xml.py
Labels: depend on
